FROM node:20-alpine

#WORKDIR /app
WORKDIR /our-trip/our-trip-front

COPY ./package.json .
#COPY ./.env ./
#COPY . .

RUN npm install
RUN npm install -g pm2

COPY . .

#COPY . .
RUN npm run build

#EXPOSE 80:80/tcp

CMD ["npm", "run", "start:pm2"]
