FROM node:20-alpine

#WORKDIR /app
WORKDIR /our-trip/our-trip-front

#COPY ./package.json ./
#COPY ./.env ./
COPY . .

RUN npm install
RUN npm run build

EXPOSE 80:80/tcp

COPY ./ ./

#CMD ["npm", "run", "build"]
CMD ["npm", "run", "start"]
