import Head from 'next/head'
import Image from 'next/image'
import { Black_Ops_One, Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css'
import HeaderComponent from "@/components/layout/HeaderComponent";
import { Col, Row } from 'antd';
import AppLayout from '@/components/layout/AppLayout';
import Map from '@/components/map/Map';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        {/*<meta name="description" content="Generated by create next app" />*/}
        {/*<meta name="viewport" content="width=device-width, initial-scale=1" />*/}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppLayout>
          {/*<h1>asdf</h1>*/}
          <Map />
        </AppLayout>
      </main>
    </>
  )
}
